### ISSUE TITLE
Some contents are hidden while trying to choose a wallet

### ISSUE THREAD

**Issue by Olaleye-Blessing** [fxhash/fxhash-website#471] opened 2022-11-05 18:16 UTC
Some of the info on wallet modal are hidden.

## Steps to reproduce
- Go to [https://www.fxhash.xyz/](https://www.fxhash.xyz/)
- Click on `sync` button on the navbar
- Notice error. The most obvious is that the button to pair wallet on another device is not fully visible

![Screenshot (157)](https://user-images.githubusercontent.com/70102539/200134915-f5b1cd8b-3f5a-457c-9bdf-aca7bd4986ac.png)

After I zoomed out

![Screenshot (156)](https://user-images.githubusercontent.com/70102539/200134941-2f851986-16a2-41a1-8c93-5cddcc6b6ca5.png)

**Comment by GemN** [comment] 2022-11-06 12:37
Hello @Olaleye-Blessing, thank you for making a GitHub issue. 

I reproduced your steps and I don't think anything wrong on my side: if the window height is small (hence covering the bottom) the beacon modal become scrollable. 

Is it scrollable on your side ?

**Comment by Olaleye-Blessing** [comment] 2022-11-09 03:36
No, it's not unless I'm missing something.

https://user-images.githubusercontent.com/70102539/200731852-6ca4ac9e-0c5b-4968-8af5-6b13bf4693e4.mp4

**Comment by maerzhase** [comment] 2022-11-09 07:20
@Olaleye-Blessing in your video you show now the settings modal and not the wallet modal

**Comment by Olaleye-Blessing** [comment] 2022-11-13 09:21
Oops! Sorry, I thought I was replying to the other issue.


https://user-images.githubusercontent.com/70102539/201514602-2f72819d-14f9-47de-9a3c-4b7eba3c3f2f.mp4

**Comment by maerzhase** [comment] 2023-01-16 18:34
@Olaleye-Blessing since i am not able to reproduce it:
is this still happening on your end? meanwhile we did some changes to modal implemenation

**Comment by GemN** [comment] 2023-01-24 13:20
@Olaleye-Blessing 
Hello, 
Can you double-check that your zoom percent is 100% when using fxhash website on Firefox?
Maybe that could lead to the problem, since we're not able to reproduce the bug - I'll close the issue. 
Let us know if you have any news

**Closed by GemN** 2023-01-24 13:20 UTC
Labels: can't reproduce
