### ISSUE TITLE
Visual bug w/ minting progress bars in marketplace view

### ISSUE THREAD

**Issue by rossgoodwin** [fxhash/fxhash-website#307] opened 2022-08-01 08:29 UTC
Just noticed this...

![image](https://user-images.githubusercontent.com/7323069/182106829-4cb4a28d-390c-45ba-9b74-0a0fdfade481.png)

Unsure how to fix this or reproduce it, or I'd submit another PR myself.

**Comment by maerzhase** [comment] 2022-08-01 08:33
think its a duplicate of #264  and should be fixed with #265

**Comment by rossgoodwin** [comment] 2022-08-04 21:16
I found it again... Duplicates this time on the page in my URL bar. 
![Screenshot_20220804-141441](https://user-images.githubusercontent.com/7323069/182954055-fc586bbd-77ca-4690-8c01-6d8dcb90f8d5.png)

**Comment by rossgoodwin** [comment] 2022-08-04 21:16
Did not mean to close. But maybe this could be merged with existing. I'd need to look at code.

**Closed** 2022-11-03 16:56 UTC
