### ISSUE TITLE
Artwork preview and thumbnail generator have different background color

### ISSUE THREAD

**Issue by jonnyscholes** [fxhash/fxhash-website#16] opened 2021-12-28 07:25 UTC
Hey,

I think https://github.com/fxhash/fxhash-website/commit/61c5c1fb4f072a97a4e401ee36526facb25a2f18 has caused a mismatch between the artwork preview and generated thumbnails.

On [this artwork](https://www.fxhash.xyz/generative/239/collection) I have not set a background color, so it uses the browser default which is usually white. Since commit https://github.com/fxhash/fxhash-website/commit/61c5c1fb4f072a97a4e401ee36526facb25a2f18 was deployed, the artwork preview now renders with a black background. However the thumbnail and live link does not have the iframe container so get a white background.

If you look at the preview for [CMYK Decay #25](https://www.fxhash.xyz/gentk/slug/cmyk-decay-25) and look at the thumbnail on the [collection page](https://www.fxhash.xyz/generative/239/collection) you can see what I mean. CMYK Decay #25 was minted 5 days ago.

Happy to submit a PR to fix this if thats helpful, although it looks like it was done to solve a specific problem 🙂

Thanks for all your hard work 🙏 let me know if I can provide any more information.

**Comment by ciphrd** [comment] 2022-01-11 11:20
Thanks for reporting.

It's tricky to solve this problem. https://github.com/fxhash/fxhash-website/commit/61c5c1fb4f072a97a4e401ee36526facb25a2f18 was added so that most artworks wouldn't get a glitched white border around them (for some reason even though the container of the iframe should take the whole space, sometimes there would be a small gap which would make the underlying background visible.

This was clearly visible on the reveal animation.

I don't think that setting the white background back is the way to go as it would make this issue appear again.

Any ideas ?

I think there should be some indications that the background of pieces should always be set in the code of the piece itself so that regardless of where the piece is displayed, the background stays the same.

**Comment by GemN** [comment] 2023-01-24 14:32
Hello @jonnyscholes 
I'm closing this issue since the problem is deprecated, at the moment ArtworkIframe will always have a white background (dark mode too), and on your example they both match the preview.
Feel free to reopen if you think the issue is not resolved

**Closed by GemN** 2023-01-24 14:32 UTC
